#!/data/data/com.termux/files/usr/bin/bash

echo "
                [*] NAME        : FARHAN MUH TASIM
                [*] WORK ONLY   : XIAOMI ALL Device 
                [*] AUTHOR      : Farhan muh tasim
                [*] Version     : FARHAN2.0
                [*] FACEBOOK    : @FARHAN MUH TASIM

"
echo "1.\033[0;33m Flash-Fastboot-ROM"
echo "2.\033[0;31m Flash-Recovery-ROM"
echo "3.\033[0;33m Unlock-Bootloader"
echo "4.\033[0;31m Root"

read -p "
Enter your choice (1/2/3/4): " \033[0;31m choice what you need 

if [ "$choice" == "1" ]; then
    python3 "$PREFIX/bin/flashfastbootrom.py"
elif [ "$choice" == "2" ]; then
    python3 "$PREFIX/bin/flashrecoveryrom.py"
elif [ "$choice" == "3" ]; then
    python3 "$PREFIX/bin/unlockbootloader.py"
elif [ "$choice" == "4" ]; then
    python3 "$PREFIX/bin/root.py"
else
    echo "
Invalid choice
"
fi
