#!/data/data/com.termux/files/usr/bin/bash

echo "
                [*] NAME        : FARHAN MUH TASIM
                [*] WORK ONLY   : XIAOMI ALL Device 
                [*] AUTHOR      : Farhan muh tasim
                [*] Version     : 4....
                [*] FACEBOOK    : @FARHAN MUH TASIM""
current_version=$(cat "$PREFIX/bin/Miui-toollV" | sed -n '1s/[^0-9.]//gp')
latest_version=$(curl -m 3 -s https://raw.githubusercontent.com/Gtajisan/Miui-tool/master/Miui-toollV | sed -n '1s/[^0-9.]//gp')
printf "\e[1;32mVersion [current:%s | latest:%s]\e[0m\n" "$current_version" "$latest_version"

if [ "$(printf "$current_version\n$latest_version" | sort -V | tail -n 1)" != "$current_version" ]; then
    update=$(curl -s https://raw.githubusercontent.com/Gtajisan/Miui-tool/master/Miui-toollV | sed '1d')
    printf "
ay abat skip prach enter new update available!:\n \e[1;32m$update\e[0m\n
"
    read -p $"(type u to update or Enter to skip..)
update MiTool? : " u
    if [ "$u" == "u" ]; then
        curl -s https://raw.githubusercontent.com/Gtajisan/Miui-tool/master/install.sh | sed -n '/files=("Miui-tool"/,/^done/p' | bash
        Miui-tool
    else
        echo "skip update .."
    fi
else
    echo
fi

echo
echo "1. Flash-Fastboot-ROM"
echo "2. Flash-Recovery-ROM"
echo "3. Unlock-Bootloader"
echo "4. Root"
echo "5. Flash-Custom-Recovery"

read -p "
Enter your choice (1/2/3/4/5): " choice

if [ "$choice" == "1" ]; then
    python3 "$PREFIX/bin/flashfastbootrom.py"
elif [ "$choice" == "2" ]; then
    python3 "$PREFIX/bin/flashrecoveryrom.py"
elif [ "$choice" == "3" ]; then
    python3 "$PREFIX/bin/unlockbootloader.py"
elif [ "$choice" == "4" ]; then
    python3 "$PREFIX/bin/root.py"
elif [ "$choice" == "5" ]; then
    python3 "$PREFIX/bin/flashcustomrecovery.py"
else
    echo "
Invalid choice
"
fi
