#!/data/data/com.termux/files/usr/bin/bash

echo "https://github.com/Gtajisan/Miui-tool"
current_version=$(cat "$PREFIX/bin/Miui-toollV" | awk -F '(' '{print $2}' | awk -F ')' '{print $1}')
latest_version=$(curl -m 0 -s https://raw.githubusercontent.com/Gtajisan/Miui-tool/master/Miui-toollV | awk -F '(' '{print $2}' | awk -F ')' '{print $1}')
printf "\e[1;32mVersion [current:%s | latest:%s]\e[0m\n" "$current_version" "$latest_version"

if [ "$(printf "$current_version\n$latest_version" | sort -V | tail -n 1)" != "$current_version" ]; then
    echo "(type u to update or Enter to skip..)
"
    update=$(curl -m 0 -s https://raw.githubusercontent.com/Gtajisan/Miui-tool/master/Miui-toollV | sed -n 's/(\(.*\))/ /p')
    read -p $"new update available!
$update
update MiTool? : " update
    if [ "$update" == "u" ]; then
        curl -m 0 -s https://raw.githubusercontent.com/Gtajisan/Miui-tool/master/install.sh | sed '/pkg update/ s/^#*/#/' | sed '/pkg upgrade/ s/^#*/#/' | bash
        exit
    else
        echo "skip update .."
    fi
else
    echo
fi

echo            [*] NAME        : FARHAN MUH TASIM
                [*] WORK ONLY   : XIAOMI ALL Device 
                [*] AUTHOR      : Farhan muh tasim
                [*] Version     : FARHAN2.0
                [*] FACEBOOK    : @FARHAN MUH TASIM



echo "1. Flash-Fastboot-ROM"
echo "2. Flash-Recovery-ROM"
echo "3. Unlock-Bootloader"
echo "4. Root"
echo "5. Flash-Custom-Recovery"

read -p "
Enter your choice (1/2/3/4/5): " choice

if [ "$choice" == "1" ]; then
    python3 "$PREFIX/bin/flashfastbootrom.py"
elif [ "$choice" == "2" ]; then
    python3 "$PREFIX/bin/flashrecoveryrom.py"
elif [ "$choice" == "3" ]; then
    python3 "$PREFIX/bin/unlockbootloader.py"
elif [ "$choice" == "4" ]; then
    python3 "$PREFIX/bin/root.py"
elif [ "$choice" == "5" ]; then
    python3 "$PREFIX/bin/flashcustomrecovery.py"
else
    echo "
Invalid choice
"
fi
